### ISSUE TITLE
Use rOpenSci pkgdown template?

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/tic#121]
https://ropensci.github.io/rotemplate/ Brand-new package and guidance so feedback welcome :wink:

**Comment by pat-s** [comment]
Cool effort providing a centralized way of building the pkgdown site!

I see that you are using `pkgdown::deploy_site_github()` which will not be supported by `tic` in the future as we rely on `travis` and do our own deployment setup in background which is also used for `blogdown`, `bookdown`, etc.

The templates are thought to be `tic.R` templates with the deployment being handed over to `tic` from `.travis.yml`. However, `pkgdown` is doing it their way directly in travis.yml which blocks tic in the end.

So to use tic in your package (if you want to do that) there would be the option to use a helper function on your side that calls

`travis::use_tic()`

and then creates the tic template for "package" which consists of two macros:

- do_package_checks()
- do_pkgdown_site()

You could tweak the "package" template to suit the ropensci needs and then provide a tic.R template in a PR. For example, change the deploy dir to "docs" instead of "gh-pages". 

To be more specific:

The `tic.R` file for installing deps, checking a pkg and building+deploying a pkgdown site will soon look like ([preview](https://github.com/ropenscilabs/tic/blob/macro-pkgdown/tic.R)):

```r
do_package_checks()

do_pkgdown_site()
```

In addition we are thinking of adding an option to the `language:r` on Travis so that the travis.yml automatically hands over to tic if the option is set, making the `.travis.yml` nearly empty.

**Comment by maelle** [comment]
We could definitely use the `tic` setup for `tic`/`travis` docs. For `rotemplate` I don't want to give that guidance before `tic` and `travis` are released on CRAN, but once they are, feel free to make a PR to update the guidance in `rotemplate` :smile_cat:

**Comment by maelle** [comment]
Also note that @jeroen is thinking of building all rOpenSci pkdown websites centrally, in which case the repos themselves won't have any Travis pkgdown stuff, so that's another thing to wait for.

**Comment by pat-s** [comment]
>  I don't want to give that guidance before tic and travis are released on CRAN, but once they are, feel free 

Sure. We might even change the name of the pkg. But it feels like we are close to start the ropensci review soon :)

> Also note that @jeroen is thinking of building all rOpenSci pkdown websites centrally, in which case the repos themselves won't have any Travis pkgdown stuff, so that's another thing to wait for.

By centrally you mean on a self-hosted jenkins instance? Or Github actions?

**Comment by maelle** [comment]
> By centrally you mean on a self-hosted jenkins instance? Or Github actions?

That part isn't certain yet. :smile_cat:

**Comment by krlmlr** [comment]
This issue seems to be about using the ropensci pkgdown template for the documentation here? Happy to.

**Comment by pat-s** [comment]
Ah, maybe I was completely wrong here - I thought it was about adapting the `rotemplate` workflow to `tic`.

Using simply the template for the site is not a problem at all and Kirill already took care of it :+1:

**Comment by krlmlr** [comment]
See https://ropenscilabs.github.io/tic/ for the new rendering.
