### ISSUE TITLE
Update template to xenial

### ISSUE THREAD

**Issue by krlmlr** [ropenscilabs/tic#160]
Some tests seem to be failing: https://github.com/ropenscilabs/tic/pull/159#issuecomment-488333646

**Comment by lorenzwalthert** [comment]
Is there any way to validate if a travis / appveyor script is still complying to a template? My hypothesis of how things could fail:

- `travis` changes something in their default specification, so to continue to use the current specification, we now need to explicitly specify the key value (e.g. an environment variable). However, all projects using `tic` have a `.travis.yml` file in their root that has no link to an upstream repo from which it could get updated. Hence, there is no way for these projects to update their CI, in worst case, they will fail silently or loudly. 
- `appveor` *depreciates* a stage / keyword in their markup language. When hard depreciation sets in after soft depreciation, all projects that use `tic` will fail with an `invalid YML specification` error.

To prevent this from happening, tic should check if the ci file such as `.travis.yml` are up to date with a template that is stored somewhere (ideally this check could be part ofa simple pre-push hook). If it is not, we should ask people to kindly update their yml file for the respective service. Also, since `tic.R` should contain all abstractions, there would actually be no reason for anyone to have specific information in the `.travis.ci`, correct? Maybe my solution is an overkill though. What do you think?

**Comment by krlmlr** [comment]
@lorenzwalthert Can you please open a new issue? This is about the Ubuntu flavor that's referred to in the template.

**Comment by krlmlr** [comment]
Can replicate failing tests locally with Git 2.21.
