### ISSUE TITLE
Error: object of type 'S4' is not subsettable

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/tic#56]
When deploying `pkgdown` docs after initializing the Git repo.

See https://travis-ci.org/r-spatial/sf/jobs/396522788

**Comment by pat-s** [comment]
This issue also occurs here: https://travis-ci.org/mlr-org/mlr/jobs/396866172

**Comment by krlmlr** [comment]
Thanks. Can you please point me to the location in the error log? You can append `#<line number>` to the job URL, or click on the line number in the log.

**Comment by pat-s** [comment]
Thanks for the hint. Here you go: https://travis-ci.org/mlr-org/mlr/jobs/396866172#2235

**Comment by krlmlr** [comment]
Thanks. I forgot that _git2r_ needs to be installed from GitHub due to breaking changes. Please file a new issue if problems persist.

**Comment by pat-s** [comment]
I tried with the dev version [here](https://travis-ci.org/mlr-org/mlr/jobs/397098260#2382) and faced a different issue.

**Comment by krlmlr** [comment]
Can you please try again with up-to-date _tic_? I don't understand how the dev version of _git2r_ is installed in the test you linked to.

**Comment by krlmlr** [comment]
I mixed it up, you need to append `#L<line number>` to the URL.

In this case it may be different, e.g. if _git2r_ is installed in the same session when it's used, but the CRAN version is already loaded because _tic_ imports _git2r_. It would be different if you added the installation to the `before_install` stage or as a preparation in a code step (`prepare_call = ...`). (`before_install` is better than `before_deploy` because in the former case the installed package will be cached.) Can you please try again with up-to-date _tic_?

**Comment by pat-s** [comment]
Ok thanks. The error is now gone, but facing different problems regarding the deployment of single files.

Will open a new issue.
