### ISSUE TITLE
Name of the package?

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/tic#72]
Stupid question maybe, but why is the package named `tic`? Wouldn't something like `ciR` or `ci` be a much more natural name for the package?

**Comment by krlmlr** [comment]
I could have sworn we already had an issue for this, but I can't find it.

I think we decided that using _ci_ as package name would work. @karthik suggested that _travis_ + _ci_ would form a nice combination too. `s/tic/ci/g' shouldn't give too many false positives, I suggest we rename shortly before submission.

**Comment by pat-s** [comment]
Should we rename before we merge the documentation?

**Comment by krlmlr** [comment]
Let's merge first.

**Comment by pat-s** [comment]
- _easycheck_

- _simplecheck_

- _rci_

- _ractions_

- _rcd_ (cont. deployment)

Does any sound good to you?

**Comment by krlmlr** [comment]
_rci_ is short and sweet.

@karthik: what do you think? Renaming everything will be a moderate pain, we can do it but should better do it before releasing to CRAN.

**Comment by pat-s** [comment]
So _rci_ then? I like it more than _tic_.

@karthik If you approve, we are one step closer to start the ropensci review :)

**Comment by krlmlr** [comment]
We need:

- [ ] a script that creates a pristine repo with the code from {tic} using a new package name
- [ ] a function that edits a repository that uses {tic} to use the new package
- [ ] deploy the renamed package as a new repo, so that `remotes::install_github("ropenscilabs/tic")` still works

That would allow us to flip the switch and at the same time reduce disruptions for existing users.

**Comment by pat-s** [comment]
I guess we concluded that there is too much hassle in renaming all related packages in addition with confusing users that already adapted the package in their daily workflow.
